version: "3.7"

services:
  charon-boot-example:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-boot-example:latest
    networks:
      - dev_overlay
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
      restart_policy:
        condition: any
    environment:
      charon.env: dev
      spring.cloud.inetutils.preferred-networks: 10.0.3
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: dev-charon-boot-example
networks:
  dev_overlay:
    external: true
