version: "3.7"

services:
  charon-boot-example:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-boot-example:latest
    networks:
      - dev_overlay
    ports:
      - "8089:8080"
    restart: always
    healthcheck:
      test: curl -f http://localhost:8080/success || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2m
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
      restart_policy:
        condition: any
        delay: 2m
      update_config:
        delay: 2m
    environment:
      charon.env: dev
      spring.cloud.inetutils.preferred-networks: 10.0.3
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: dev-charon-boot-example
networks:
  dev_overlay:
    external: true
