version: "3.7"

services:
  charon-boot-example:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-boot-example:latest
    networks:
      - dev_overlay
    ports:
      - "8089:8080"
    healthcheck:
      test: curl -f http://localhost:8080/status |grep 'success' || exit 1
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 10m
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10m
    environment:
      charon.env: dev
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.org:11800
      SW_AGENT_NAME: dev-charon-boot-example
    extra_hosts:
      - "sw.dev.kikera.org:10.144.106.92"
networks:
  dev_overlay:
    external: true
